export interface EventService {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  price: string;
  details?: string;
  capacity?: string;
  location?: string;
  rating: number;
  reviews: number;
  availability: string;
  image?: string;
  normalUserOffer?: string;
  vipUserOffer?: string;
  phone?: string;
}

export const eventCategories = [
  "Decoration",
  "Tent House",
  "DJ & Lighting",
  "Thadakala Pandiri",
  "Function Halls",
  "Catering",
  "Mehendi Art",
  "Photography",
  "Chef",
] as const;

export type EventCategoryKey = typeof eventCategories[number];

export const eventData: EventService[] = [
  // Decoration
  {
    id: "birthday-decoration",
    name: "Birthday Decoration",
    description: "Celebrate More, Spend Less! We customize decorations to fit your budget",
    category: "Decoration",
    icon: "gift",
    price: "Starting at ₹1,499",
    details: "Custom decorations for all budgets",
    rating: 4.8,
    reviews: 1200,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/decoration/bdy/1.jpg",
    normalUserOffer: "Basic decoration: ₹1,499\nStandard theme: 15% off\nPhotography: ₹2,000\nCatering: 10% off",
    vipUserOffer: "Premium decoration: 30% off\nLuxury theme: 25% off\nProfessional photography: 20% off\nPremium catering: 20% off\nFree event coordination",
    phone: "8247556370",
  },
  {
    id: "haldi-decoration",
    name: "Haldi Decoration",
    description: "Celebrate with Elegance! Custom decorations for your special day",
    category: "Decoration",
    icon: "flower",
    price: "Starting at ₹2,999",
    details: "Elegant haldi ceremony decorations",
    rating: 4.7,
    reviews: 980,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/decoration/haldi/1.jpg",
    normalUserOffer: "Haldi decoration: ₹2,999\nTraditional theme: 15% off\nPhotography: ₹2,500\nCatering: 10% off",
    vipUserOffer: "Premium haldi decoration: 30% off\nLuxury traditional theme: 25% off\nProfessional photography: 20% off\nPremium catering: 20% off\nFree event coordination",
    phone: "8247556370",
  },
  {
    id: "wedding-decoration",
    name: "Wedding Decoration",
    description: "Make Your Big Day Special! Custom wedding decor to suit your style",
    category: "Decoration",
    icon: "heart",
    price: "Starting at ₹9,999",
    details: "Complete wedding decoration packages",
    rating: 4.9,
    reviews: 1500,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/decoration/wedding/4.jpg",
    phone: "8247556370",
  },
  {
    id: "reception-decoration",
    name: "Reception Decoration",
    description: "Customized reception themes for all budgets",
    category: "Decoration",
    icon: "sparkles",
    price: "Starting at ₹5,999",
    details: "Elegant reception setups",
    rating: 4.6,
    reviews: 750,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1676734627786-a3662ff6a243?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phone: "8247556370",
  },
  {
    id: "premium-decorations",
    name: "Premium Decorations",
    description: "Premium Decorations at Budget-Friendly Prices",
    category: "Decoration",
    icon: "diamond",
    price: "Guaranteed Lowest Price",
    details: "Elegant premium setups",
    rating: 4.8,
    reviews: 1100,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/decoration/wedding/2.jpg",
    phone: "8247556370",
  },
  // Tent House
  {
    id: "tent-house-services",
    name: "Tent House Services",
    description: "Complete tent setup for all your outdoor events",
    category: "Tent House",
    icon: "home",
    price: "Lowest Price Guarantee",
    details: "Professional tent house services",
    rating: 4.7,
    reviews: 890,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1655409735952-cb5220efca54?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    phone: "8247556370",
  },
  // DJ & Lighting
  {
    id: "dj-services",
    name: "DJ Services",
    description: "Premium Sound Systems at Budget-Friendly Prices",
    category: "DJ & Lighting",
    icon: "musical-notes",
    price: "Starting at ₹2,999",
    details: "Professional DJ with latest equipment",
    rating: 4.8,
    reviews: 1300,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/dj-lighting/dj/1.jpeg",
    phone: "8247556370",
  },
  {
    id: "lighting-services",
    name: "Lighting Services",
    description: "LED lights for Home & Street events",
    category: "DJ & Lighting",
    icon: "bulb",
    price: "Starting at ₹999",
    details: "Professional lighting solutions",
    rating: 4.6,
    reviews: 720,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/dj-lighting/lighting/2.jpg",
    phone: "8247556370",
  },
  // Thadakala Pandiri
  {
    id: "thadakala-pandiri",
    name: "Thadakala Pandiri",
    description: "Traditional Pandiri Setup for Weddings",
    category: "Thadakala Pandiri",
    icon: "leaf",
    price: "Budget Friendly & Lowest Price",
    details: "Authentic traditional setup",
    rating: 4.9,
    reviews: 950,
    availability: "Available Now",
    image: "https://5.imimg.com/data5/ANDROID/Default/2020/12/AK/ID/JL/31748740/product-jpeg-500x500.jpg",
    phone: "8247556370",
  },
  // Function Halls
  {
    id: "vasavi-kalyana-mandapam",
    name: "VASAVI Kalyana Mandapam (A/C)",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Starting at ₹29,999",
    capacity: "Capacity: 400-600 People",
    location: "Gandhi Nagar, Sircilla",
    rating: 4.8,
    reviews: 1200,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/vasavi-kalyana-mandapam-a-c/2.webp",
    phone: "8247556370",
  },
  {
    id: "padmashali-kalyana-mandapam",
    name: "Padmashali Kalyana Mandapam",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Starting at ₹29,999",
    capacity: "Capacity: 400-600 People",
    location: "Gandhi Nagar, Sircilla",
    rating: 4.7,
    reviews: 980,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/vasavi-kalyana-mandapam-a-c/1.webp",
    phone: "8247556370",
  },
  {
    id: "sai-manikanta-gardens",
    name: "Sai Manikanta Gardens (A/C)",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Contact for Quote",
    capacity: "Capacity: 1000-1500 People",
    location: "Ragudu, Karimnagar Road, Sircilla",
    rating: 4.9,
    reviews: 1500,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/lahari-function-hall/3.webp",
    phone: "8247556370",
  },
  {
    id: "lahari-grand-function-hall",
    name: "Lahari Grand Function Hall",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Contact for Quote",
    capacity: "Capacity: 800-1000 People",
    location: "Siddipet Road, Sircilla",
    rating: 4.8,
    reviews: 1100,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/lahari-function-hall/2.webp",
    phone: "8247556370",
  },
  {
    id: "k-convention-hall",
    name: "K Convention Hall",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Contact for Quote",
    capacity: "Capacity: 800-1000 People",
    location: "Bypass Road, Sircilla",
    rating: 4.6,
    reviews: 750,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/k-function-hall/1.webp",
    phone: "8247556370",
  },
  {
    id: "maanya-banquet-hall",
    name: "Maanya A/C Banquet Hall",
    description: "Weddings, Functions & Meetings",
    category: "Function Halls",
    icon: "business",
    price: "Contact for Quote",
    capacity: "Capacity: 800-1000 People",
    location: "Goldsmith Street, Main Bazar, Sircilla",
    rating: 4.7,
    reviews: 890,
    availability: "Available Now",
    image: "https://rwrwadrkgnbiekvlrpza.supabase.co/storage/v1/object/public/dm-images/events-services/function-halls/maanya-a-c-banquet-hall/2.jpg",
    phone: "8247556370",
  },
  // Catering
  {
    id: "vinayaka-catering",
    name: "Vinayaka Catering",
    description: "Delicious Catering for Weddings & Functions",
    category: "Catering",
    icon: "restaurant",
    price: "Starting from ₹99 per person",
    details: "Minimum 200 People | Veg & Non-Veg available | Professional staff",
    rating: 4.8,
    reviews: 1800,
    availability: "Available Now",
    image: "https://plus.unsplash.com/premium_photo-1686239357900-febfb958f33c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2F0ZXJpbmd8ZW58MHx8MHx8fDA%3D",
    phone: "8247556370",
  },
  {
    id: "catering-staff-service",
    name: "Catering Staff Service",
    description: "Trained serving staff for weddings & functions",
    category: "Catering",
    icon: "people",
    price: "Starting from ₹499 per person",
    details: "30% lower than market rates",
    rating: 4.6,
    reviews: 650,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1518619745898-93e765966dcd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2F0ZXJpbmd8ZW58MHx8MHx8fDA%3D",
    phone: "8247556370",
  },
  // Mehendi Art
  {
    id: "mehendi-art",
    name: "Mehendi Art",
    description: "Beautiful Mehendi Art Services",
    category: "Mehendi Art",
    icon: "brush",
    price: "Starting from ₹299 per hand",
    details: "Natural & Chemical-Free Mehendi Paste",
    rating: 4.7,
    reviews: 950,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1505932794465-147d1f1b2c97?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWVoZW5kaXxlbnwwfHwwfHx8MA%3D%3D",
    phone: "8247556370",
  },
  // Photography (New)
  {
    id: "photography-service",
    name: "Professional Photography",
    description: "Birthday, Wedding, Functions & More",
    category: "Photography",
    icon: "camera",
    price: "Custom Quote",
    details: "Select event type and submit a request",
    rating: 4.8,
    reviews: 540,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=60",
    phone: "8247556370",
  },
  // Chef (New)
  {
    id: "chef-service",
    name: "Chef Service",
    description: "Home or Function Hall – 1 to 5 Days",
    category: "Chef",
    icon: "restaurant",
    price: "Custom Quote",
    details: "Tell us venue type, days and date",
    rating: 4.7,
    reviews: 410,
    availability: "Available Now",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&auto=format&fit=crop&q=60",
    phone: "8247556370",
  },
];

export const getEventServiceById = (id: string) => eventData.find(service => service.id === id);

export const getEventServicesByCategory = (category: EventCategoryKey) => 
  eventData.filter(service => service.category === category);
